// Code generated by gen.py from testdata/sample.xml; DO NOT EDIT.

package flex

// Each struct mirrors one element of the Flex report XML. Fields bind by
// attribute name, so a query may select any subset of columns; unselected
// columns and unmodeled sections are simply absent. Numeric attributes use
// Float, which decodes an empty attribute as 0. Dates, identifiers, and codes
// are kept as strings because their formats are query-configurable. Several
// elements (trade detail levels; FX position and lot) share an identical
// attribute set and therefore a single Go type. To regenerate, run
// 'go generate ./flex' after refreshing testdata/sample.xml.

type AccountInformation struct {
	AccountCapabilities          string `xml:"accountCapabilities,attr"`
	AccountID                    string `xml:"accountId,attr"`
	AccountRepName               string `xml:"accountRepName,attr"`
	AccountRepPhone              string `xml:"accountRepPhone,attr"`
	AccountType                  string `xml:"accountType,attr"`
	AcctAlias                    string `xml:"acctAlias,attr"`
	BeneficiaryDesignations      string `xml:"beneficiaryDesignations,attr"`
	City                         string `xml:"city,attr"`
	CityResidentialAddress       string `xml:"cityResidentialAddress,attr"`
	Country                      string `xml:"country,attr"`
	CountryResidentialAddress    string `xml:"countryResidentialAddress,attr"`
	Currency                     string `xml:"currency,attr"`
	CustomerType                 string `xml:"customerType,attr"`
	DateClosed                   string `xml:"dateClosed,attr"`
	DateFunded                   string `xml:"dateFunded,attr"`
	DateOfBirth                  string `xml:"dateOfBirth,attr"`
	DateOpened                   string `xml:"dateOpened,attr"`
	DividendReinvestmentEnabled  string `xml:"dividendReinvestmentEnabled,attr"`
	HasPendingTasks              string `xml:"hasPendingTasks,attr"`
	IbEntity                     string `xml:"ibEntity,attr"`
	LastTradedDate               string `xml:"lastTradedDate,attr"`
	MasterName                   string `xml:"masterName,attr"`
	Model                        string `xml:"model,attr"`
	Name                         string `xml:"name,attr"`
	PostalCode                   string `xml:"postalCode,attr"`
	PostalCodeResidentialAddress string `xml:"postalCodeResidentialAddress,attr"`
	PrimaryEmail                 string `xml:"primaryEmail,attr"`
	RecurringTransactions        string `xml:"recurringTransactions,attr"`
	State                        string `xml:"state,attr"`
	StateResidentialAddress      string `xml:"stateResidentialAddress,attr"`
	Street                       string `xml:"street,attr"`
	Street2                      string `xml:"street2,attr"`
	Street2ResidentialAddress    string `xml:"street2ResidentialAddress,attr"`
	StreetResidentialAddress     string `xml:"streetResidentialAddress,attr"`
	SyepEnrollmentStatus         string `xml:"syepEnrollmentStatus,attr"`
	TaxLotMatchingMethod         string `xml:"taxLotMatchingMethod,attr"`
	TradingPermissions           string `xml:"tradingPermissions,attr"`
}

type CashTransaction struct {
	AccountID                 string `xml:"accountId,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	ActionID                  string `xml:"actionID,attr"`
	Amount                    Float  `xml:"amount,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	AvailableForTradingDate   string `xml:"availableForTradingDate,attr"`
	ClientReference           string `xml:"clientReference,attr"`
	Code                      string `xml:"code,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	Currency                  string `xml:"currency,attr"`
	Cusip                     string `xml:"cusip,attr"`
	DateTime                  string `xml:"dateTime,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	DividendType              string `xml:"dividendType,attr"`
	ExDate                    string `xml:"exDate,attr"`
	Expiry                    string `xml:"expiry,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	FxRateToBase              Float  `xml:"fxRateToBase,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	LevelOfDetail             string `xml:"levelOfDetail,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	Model                     string `xml:"model,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	PutCall                   string `xml:"putCall,attr"`
	ReportDate                string `xml:"reportDate,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	SettleDate                string `xml:"settleDate,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	TradeID                   string `xml:"tradeID,attr"`
	TransactionID             string `xml:"transactionID,attr"`
	Type                      string `xml:"type,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	Weight                    Float  `xml:"weight,attr"`
}

type CashTransactions struct {
	CashTransaction []CashTransaction `xml:"CashTransaction"`
}

type CommissionCredits struct {
	Unmodeled []RawElement `xml:",any"`
}

type CorporateActions struct {
	Unmodeled []RawElement `xml:",any"`
}

type FIFOPerformanceSummaryInBase struct {
	FIFOPerformanceSummaryUnderlying []FIFOPerformanceSummaryUnderlying `xml:"FIFOPerformanceSummaryUnderlying"`
}

type FIFOPerformanceSummaryUnderlying struct {
	AccountID                 string `xml:"accountId,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	Code                      string `xml:"code,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	CostAdj                   Float  `xml:"costAdj,attr"`
	Cusip                     string `xml:"cusip,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	Expiry                    string `xml:"expiry,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	Model                     string `xml:"model,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	PutCall                   string `xml:"putCall,attr"`
	RealizedLTLoss            Float  `xml:"realizedLTLoss,attr"`
	RealizedLTProfit          Float  `xml:"realizedLTProfit,attr"`
	RealizedSTLoss            Float  `xml:"realizedSTLoss,attr"`
	RealizedSTProfit          Float  `xml:"realizedSTProfit,attr"`
	ReportDate                string `xml:"reportDate,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	TotalFifoPnl              Float  `xml:"totalFifoPnl,attr"`
	TotalRealizedPnl          Float  `xml:"totalRealizedPnl,attr"`
	TotalUnrealizedPnl        Float  `xml:"totalUnrealizedPnl,attr"`
	TransferredPnl            Float  `xml:"transferredPnl,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	UnrealizedLTLoss          Float  `xml:"unrealizedLTLoss,attr"`
	UnrealizedLTProfit        Float  `xml:"unrealizedLTProfit,attr"`
	UnrealizedLoss            Float  `xml:"unrealizedLoss,attr"`
	UnrealizedProfit          Float  `xml:"unrealizedProfit,attr"`
	UnrealizedSTLoss          Float  `xml:"unrealizedSTLoss,attr"`
	UnrealizedSTProfit        Float  `xml:"unrealizedSTProfit,attr"`
	Weight                    Float  `xml:"weight,attr"`
}

type FxLot struct {
	AccountID          string `xml:"accountId,attr"`
	AcctAlias          string `xml:"acctAlias,attr"`
	AssetCategory      string `xml:"assetCategory,attr"`
	ClosePrice         Float  `xml:"closePrice,attr"`
	Code               string `xml:"code,attr"`
	CostBasis          Float  `xml:"costBasis,attr"`
	CostPrice          Float  `xml:"costPrice,attr"`
	FunctionalCurrency string `xml:"functionalCurrency,attr"`
	FxCurrency         string `xml:"fxCurrency,attr"`
	LevelOfDetail      string `xml:"levelOfDetail,attr"`
	LotDescription     string `xml:"lotDescription,attr"`
	LotOpenDateTime    string `xml:"lotOpenDateTime,attr"`
	Model              string `xml:"model,attr"`
	Quantity           Float  `xml:"quantity,attr"`
	ReportDate         string `xml:"reportDate,attr"`
	UnrealizedPL       Float  `xml:"unrealizedPL,attr"`
	Value              Float  `xml:"value,attr"`
}

type FxLots struct {
	FxLot []FxLot `xml:"FxLot"`
}

type FxPositions struct {
	FxLots     FxLots  `xml:"FxLots"`
	FxPosition []FxLot `xml:"FxPosition"`
}

type HardToBorrowDetail struct {
	AccountID                 string `xml:"accountId,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	BorrowFee                 Float  `xml:"borrowFee,attr"`
	BorrowFeeRate             Float  `xml:"borrowFeeRate,attr"`
	Code                      string `xml:"code,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	Currency                  string `xml:"currency,attr"`
	Cusip                     string `xml:"cusip,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	Expiry                    string `xml:"expiry,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	FromAcct                  string `xml:"fromAcct,attr"`
	FxRateToBase              Float  `xml:"fxRateToBase,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	Model                     string `xml:"model,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	Price                     Float  `xml:"price,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	PutCall                   string `xml:"putCall,attr"`
	Quantity                  Float  `xml:"quantity,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	ToAcct                    string `xml:"toAcct,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	Value                     Float  `xml:"value,attr"`
	ValueDate                 string `xml:"valueDate,attr"`
	Weight                    Float  `xml:"weight,attr"`
}

type HardToBorrowDetails struct {
	HardToBorrowDetail []HardToBorrowDetail `xml:"HardToBorrowDetail"`
}

type InterestAccruals struct {
	InterestAccrualsCurrency []InterestAccrualsCurrency `xml:"InterestAccrualsCurrency"`
}

type InterestAccrualsCurrency struct {
	AccountID              string `xml:"accountId,attr"`
	AccrualReversal        Float  `xml:"accrualReversal,attr"`
	Currency               string `xml:"currency,attr"`
	EndingAccrualBalance   Float  `xml:"endingAccrualBalance,attr"`
	FromDate               string `xml:"fromDate,attr"`
	FxTranslation          Float  `xml:"fxTranslation,attr"`
	InterestAccrued        Float  `xml:"interestAccrued,attr"`
	Model                  string `xml:"model,attr"`
	StartingAccrualBalance Float  `xml:"startingAccrualBalance,attr"`
	ToDate                 string `xml:"toDate,attr"`
}

type OpenDividendAccruals struct {
	Unmodeled []RawElement `xml:",any"`
}

type OpenPosition struct {
	AccountID                 string `xml:"accountId,attr"`
	AccruedInt                Float  `xml:"accruedInt,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	Code                      string `xml:"code,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	CostBasisMoney            Float  `xml:"costBasisMoney,attr"`
	CostBasisPrice            Float  `xml:"costBasisPrice,attr"`
	Currency                  string `xml:"currency,attr"`
	Cusip                     string `xml:"cusip,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	Expiry                    string `xml:"expiry,attr"`
	FifoPnlUnrealized         Float  `xml:"fifoPnlUnrealized,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	FxRateToBase              Float  `xml:"fxRateToBase,attr"`
	HoldingPeriodDateTime     string `xml:"holdingPeriodDateTime,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	LevelOfDetail             string `xml:"levelOfDetail,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	MarkPrice                 Float  `xml:"markPrice,attr"`
	Model                     string `xml:"model,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	OpenDateTime              string `xml:"openDateTime,attr"`
	OpenPrice                 Float  `xml:"openPrice,attr"`
	OriginatingOrderID        string `xml:"originatingOrderID,attr"`
	OriginatingTransactionID  string `xml:"originatingTransactionID,attr"`
	PercentOfNAV              Float  `xml:"percentOfNAV,attr"`
	Position                  Float  `xml:"position,attr"`
	PositionValue             Float  `xml:"positionValue,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	PutCall                   string `xml:"putCall,attr"`
	ReportDate                string `xml:"reportDate,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	Side                      string `xml:"side,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	VestingDate               string `xml:"vestingDate,attr"`
	Weight                    Float  `xml:"weight,attr"`
}

type OpenPositions struct {
	OpenPosition []OpenPosition `xml:"OpenPosition"`
}

type OptionEAE struct {
	AccountID                 string `xml:"accountId,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	CommisionsAndTax          Float  `xml:"commisionsAndTax,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	CostBasis                 Float  `xml:"costBasis,attr"`
	Currency                  string `xml:"currency,attr"`
	Cusip                     string `xml:"cusip,attr"`
	Date                      string `xml:"date,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	Expiry                    string `xml:"expiry,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	FxPnl                     Float  `xml:"fxPnl,attr"`
	FxRateToBase              Float  `xml:"fxRateToBase,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	MarkPrice                 Float  `xml:"markPrice,attr"`
	Model                     string `xml:"model,attr"`
	MtmPnl                    Float  `xml:"mtmPnl,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	Proceeds                  Float  `xml:"proceeds,attr"`
	PutCall                   string `xml:"putCall,attr"`
	Quantity                  Float  `xml:"quantity,attr"`
	RealizedPnl               Float  `xml:"realizedPnl,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	TradeID                   string `xml:"tradeID,attr"`
	TradePrice                Float  `xml:"tradePrice,attr"`
	TransactionType           string `xml:"transactionType,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	Weight                    Float  `xml:"weight,attr"`
}

type SLBActivities struct {
	SLBActivity []SLBActivity `xml:"SLBActivity"`
}

type SLBActivity struct {
	AccountID                 string `xml:"accountId,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	ActivityDescription       string `xml:"activityDescription,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	BasePrice                 Float  `xml:"basePrice,attr"`
	CollateralAmount          Float  `xml:"collateralAmount,attr"`
	CollateralPercentage      Float  `xml:"collateralPercentage,attr"`
	CollateralPrice           Float  `xml:"collateralPrice,attr"`
	CollateralRoundingRule    string `xml:"collateralRoundingRule,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	Currency                  string `xml:"currency,attr"`
	Cusip                     string `xml:"cusip,attr"`
	Date                      string `xml:"date,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	Exchange                  string `xml:"exchange,attr"`
	Expiry                    string `xml:"expiry,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	FxRateToBase              Float  `xml:"fxRateToBase,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	MarkCurrentPrice          Float  `xml:"markCurrentPrice,attr"`
	MarkPriorPrice            Float  `xml:"markPriorPrice,attr"`
	MarkQuantity              Float  `xml:"markQuantity,attr"`
	Model                     string `xml:"model,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	PutCall                   string `xml:"putCall,attr"`
	Quantity                  Float  `xml:"quantity,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	SlbTransactionID          string `xml:"slbTransactionId,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	Type                      string `xml:"type,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	Weight                    Float  `xml:"weight,attr"`
}

type SLBCollateral struct {
	AccountID                 string `xml:"accountId,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	Currency                  string `xml:"currency,attr"`
	Cusip                     string `xml:"cusip,attr"`
	Date                      string `xml:"date,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	Expiry                    string `xml:"expiry,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	FxRateToBase              Float  `xml:"fxRateToBase,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	Model                     string `xml:"model,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	Price                     Float  `xml:"price,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	PutCall                   string `xml:"putCall,attr"`
	Quantity                  Float  `xml:"quantity,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	Type                      string `xml:"type,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	Value                     Float  `xml:"value,attr"`
	Weight                    Float  `xml:"weight,attr"`
}

type SLBCollaterals struct {
	SLBCollateral []SLBCollateral `xml:"SLBCollateral"`
}

type SLBFee struct {
	AccountID                 string `xml:"accountId,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	CarryCharge               Float  `xml:"carryCharge,attr"`
	Code                      string `xml:"code,attr"`
	CollateralAmount          Float  `xml:"collateralAmount,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	Currency                  string `xml:"currency,attr"`
	Cusip                     string `xml:"cusip,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	Exchange                  string `xml:"exchange,attr"`
	Expiry                    string `xml:"expiry,attr"`
	Fee                       Float  `xml:"fee,attr"`
	FeeRate                   Float  `xml:"feeRate,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	FromAcct                  string `xml:"fromAcct,attr"`
	FxRateToBase              Float  `xml:"fxRateToBase,attr"`
	GrossLendFee              Float  `xml:"grossLendFee,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	MarketFeeRate             Float  `xml:"marketFeeRate,attr"`
	Model                     string `xml:"model,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	NetLendFee                Float  `xml:"netLendFee,attr"`
	NetLendFeeRate            Float  `xml:"netLendFeeRate,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	PutCall                   string `xml:"putCall,attr"`
	Quantity                  Float  `xml:"quantity,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	StartDate                 string `xml:"startDate,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	TicketCharge              Float  `xml:"ticketCharge,attr"`
	ToAcct                    string `xml:"toAcct,attr"`
	TotalCharges              Float  `xml:"totalCharges,attr"`
	Type                      string `xml:"type,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	UniqueID                  string `xml:"uniqueID,attr"`
	ValueDate                 string `xml:"valueDate,attr"`
	Weight                    Float  `xml:"weight,attr"`
}

type SLBFees struct {
	SLBFee []SLBFee `xml:"SLBFee"`
}

type SLBOpenContract struct {
	AccountID                 string `xml:"accountId,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	BasePrice                 Float  `xml:"basePrice,attr"`
	CollateralAmount          Float  `xml:"collateralAmount,attr"`
	CollateralPercentage      Float  `xml:"collateralPercentage,attr"`
	CollateralPrice           Float  `xml:"collateralPrice,attr"`
	CollateralRoundingRule    string `xml:"collateralRoundingRule,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	Currency                  string `xml:"currency,attr"`
	Cusip                     string `xml:"cusip,attr"`
	Date                      string `xml:"date,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	ExcessQuantity            Float  `xml:"excessQuantity,attr"`
	Exchange                  string `xml:"exchange,attr"`
	Expiry                    string `xml:"expiry,attr"`
	FeeRate                   Float  `xml:"feeRate,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	FxRateToBase              Float  `xml:"fxRateToBase,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	LevelOfDetail             string `xml:"levelOfDetail,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	Model                     string `xml:"model,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	PutCall                   string `xml:"putCall,attr"`
	Quantity                  Float  `xml:"quantity,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	SlbTransactionID          string `xml:"slbTransactionId,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	Type                      string `xml:"type,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	Weight                    Float  `xml:"weight,attr"`
}

type SLBOpenContracts struct {
	SLBOpenContract []SLBOpenContract `xml:"SLBOpenContract"`
}

type Statement struct {
	AccountID                    string                       `xml:"accountId,attr"`
	FromDate                     string                       `xml:"fromDate,attr"`
	Period                       string                       `xml:"period,attr"`
	ToDate                       string                       `xml:"toDate,attr"`
	WhenGenerated                string                       `xml:"whenGenerated,attr"`
	AccountInformation           []AccountInformation         `xml:"AccountInformation"`
	CashTransactions             CashTransactions             `xml:"CashTransactions"`
	CommissionCredits            CommissionCredits            `xml:"CommissionCredits"`
	CorporateActions             CorporateActions             `xml:"CorporateActions"`
	FIFOPerformanceSummaryInBase FIFOPerformanceSummaryInBase `xml:"FIFOPerformanceSummaryInBase"`
	FxPositions                  FxPositions                  `xml:"FxPositions"`
	HardToBorrowDetails          HardToBorrowDetails          `xml:"HardToBorrowDetails"`
	InterestAccruals             InterestAccruals             `xml:"InterestAccruals"`
	OpenDividendAccruals         OpenDividendAccruals         `xml:"OpenDividendAccruals"`
	OpenPositions                OpenPositions                `xml:"OpenPositions"`
	OptionEAE                    []OptionEAE                  `xml:"OptionEAE>OptionEAE"`
	SLBActivities                SLBActivities                `xml:"SLBActivities"`
	SLBCollaterals               SLBCollaterals               `xml:"SLBCollaterals"`
	SLBFees                      SLBFees                      `xml:"SLBFees"`
	SLBOpenContracts             SLBOpenContracts             `xml:"SLBOpenContracts"`
	StmtFunds                    StmtFunds                    `xml:"StmtFunds"`
	TierInterestDetails          TierInterestDetails          `xml:"TierInterestDetails"`
	TradeTransfers               TradeTransfers               `xml:"TradeTransfers"`
	Trades                       Trades                       `xml:"Trades"`
	TransactionTaxes             TransactionTaxes             `xml:"TransactionTaxes"`
	Transfers                    Transfers                    `xml:"Transfers"`
	UnbundledCommissionDetails   UnbundledCommissionDetails   `xml:"UnbundledCommissionDetails"`
}

type StatementOfFundsLine struct {
	AccountID                 string `xml:"accountId,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	ActionID                  string `xml:"actionID,attr"`
	ActivityCode              string `xml:"activityCode,attr"`
	ActivityDescription       string `xml:"activityDescription,attr"`
	Amount                    Float  `xml:"amount,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	Balance                   Float  `xml:"balance,attr"`
	BuySell                   string `xml:"buySell,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	Credit                    Float  `xml:"credit,attr"`
	Currency                  string `xml:"currency,attr"`
	Cusip                     string `xml:"cusip,attr"`
	Date                      string `xml:"date,attr"`
	Debit                     Float  `xml:"debit,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	Expiry                    string `xml:"expiry,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	FxRateToBase              Float  `xml:"fxRateToBase,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	LevelOfDetail             string `xml:"levelOfDetail,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	Model                     string `xml:"model,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	OrderID                   string `xml:"orderID,attr"`
	OrigTransactionID         string `xml:"origTransactionID,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	PutCall                   string `xml:"putCall,attr"`
	RelatedTradeID            string `xml:"relatedTradeID,attr"`
	RelatedTransactionID      string `xml:"relatedTransactionID,attr"`
	ReportDate                string `xml:"reportDate,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	SettleDate                string `xml:"settleDate,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	TradeCode                 string `xml:"tradeCode,attr"`
	TradeCommission           Float  `xml:"tradeCommission,attr"`
	TradeGross                Float  `xml:"tradeGross,attr"`
	TradeID                   string `xml:"tradeID,attr"`
	TradePrice                Float  `xml:"tradePrice,attr"`
	TradeQuantity             Float  `xml:"tradeQuantity,attr"`
	TradeTax                  Float  `xml:"tradeTax,attr"`
	TransactionID             string `xml:"transactionID,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	Weight                    Float  `xml:"weight,attr"`
}

type StmtFunds struct {
	StatementOfFundsLine []StatementOfFundsLine `xml:"StatementOfFundsLine"`
}

type TierInterestDetail struct {
	AccountID            string `xml:"accountId,attr"`
	AcctAlias            string `xml:"acctAlias,attr"`
	BalanceThreshold     Float  `xml:"balanceThreshold,attr"`
	Code                 string `xml:"code,attr"`
	CommoditiesInterest  Float  `xml:"commoditiesInterest,attr"`
	CommoditiesPrincipal Float  `xml:"commoditiesPrincipal,attr"`
	Currency             string `xml:"currency,attr"`
	FromAcct             string `xml:"fromAcct,attr"`
	FxRateToBase         Float  `xml:"fxRateToBase,attr"`
	IbuklInterest        Float  `xml:"ibuklInterest,attr"`
	IbuklPrincipal       Float  `xml:"ibuklPrincipal,attr"`
	InterestType         string `xml:"interestType,attr"`
	MarginBalance        string `xml:"marginBalance,attr"`
	Model                string `xml:"model,attr"`
	Rate                 Float  `xml:"rate,attr"`
	ReportDate           string `xml:"reportDate,attr"`
	SecuritiesInterest   Float  `xml:"securitiesInterest,attr"`
	SecuritiesPrincipal  Float  `xml:"securitiesPrincipal,attr"`
	TierBreak            string `xml:"tierBreak,attr"`
	ToAcct               string `xml:"toAcct,attr"`
	TotalInterest        Float  `xml:"totalInterest,attr"`
	TotalPrincipal       Float  `xml:"totalPrincipal,attr"`
	ValueDate            string `xml:"valueDate,attr"`
}

type TierInterestDetails struct {
	TierInterestDetail []TierInterestDetail `xml:"TierInterestDetail"`
}

type Trade struct {
	AccountID                 string `xml:"accountId,attr"`
	AccruedInt                Float  `xml:"accruedInt,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	BrokerageOrderID          string `xml:"brokerageOrderID,attr"`
	BuySell                   string `xml:"buySell,attr"`
	ChangeInPrice             Float  `xml:"changeInPrice,attr"`
	ChangeInQuantity          Float  `xml:"changeInQuantity,attr"`
	ClearingFirmID            string `xml:"clearingFirmID,attr"`
	ClosePrice                Float  `xml:"closePrice,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	Cost                      Float  `xml:"cost,attr"`
	Currency                  string `xml:"currency,attr"`
	Cusip                     string `xml:"cusip,attr"`
	DateTime                  string `xml:"dateTime,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	ExchOrderID               string `xml:"exchOrderId,attr"`
	Exchange                  string `xml:"exchange,attr"`
	Expiry                    string `xml:"expiry,attr"`
	ExtExecID                 string `xml:"extExecID,attr"`
	FifoPnlRealized           Float  `xml:"fifoPnlRealized,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	FxRateToBase              Float  `xml:"fxRateToBase,attr"`
	HoldingPeriodDateTime     string `xml:"holdingPeriodDateTime,attr"`
	IbCommission              Float  `xml:"ibCommission,attr"`
	IbCommissionCurrency      string `xml:"ibCommissionCurrency,attr"`
	IbExecID                  string `xml:"ibExecID,attr"`
	IbOrderID                 string `xml:"ibOrderID,attr"`
	InitialInvestment         string `xml:"initialInvestment,attr"`
	IsAPIOrder                string `xml:"isAPIOrder,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	LevelOfDetail             string `xml:"levelOfDetail,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	Model                     string `xml:"model,attr"`
	MtmPnl                    Float  `xml:"mtmPnl,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	NetCash                   Float  `xml:"netCash,attr"`
	Notes                     string `xml:"notes,attr"`
	OpenCloseIndicator        string `xml:"openCloseIndicator,attr"`
	OpenDateTime              string `xml:"openDateTime,attr"`
	OrderReference            string `xml:"orderReference,attr"`
	OrderTime                 string `xml:"orderTime,attr"`
	OrderType                 string `xml:"orderType,attr"`
	OrigOrderID               string `xml:"origOrderID,attr"`
	OrigTradeDate             string `xml:"origTradeDate,attr"`
	OrigTradeID               string `xml:"origTradeID,attr"`
	OrigTradePrice            Float  `xml:"origTradePrice,attr"`
	OrigTransactionID         string `xml:"origTransactionID,attr"`
	PositionActionID          string `xml:"positionActionID,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	Proceeds                  Float  `xml:"proceeds,attr"`
	PutCall                   string `xml:"putCall,attr"`
	Quantity                  Float  `xml:"quantity,attr"`
	RelatedTradeID            string `xml:"relatedTradeID,attr"`
	RelatedTransactionID      string `xml:"relatedTransactionID,attr"`
	ReportDate                string `xml:"reportDate,attr"`
	Rtn                       string `xml:"rtn,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	SettleDateTarget          string `xml:"settleDateTarget,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	Taxes                     Float  `xml:"taxes,attr"`
	TradeDate                 string `xml:"tradeDate,attr"`
	TradeID                   string `xml:"tradeID,attr"`
	TradeMoney                Float  `xml:"tradeMoney,attr"`
	TradePrice                Float  `xml:"tradePrice,attr"`
	TraderID                  string `xml:"traderID,attr"`
	TransactionID             string `xml:"transactionID,attr"`
	TransactionType           string `xml:"transactionType,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	VolatilityOrderLink       string `xml:"volatilityOrderLink,attr"`
	Weight                    Float  `xml:"weight,attr"`
	WhenRealized              string `xml:"whenRealized,attr"`
	WhenReopened              string `xml:"whenReopened,attr"`
}

type TradeTransfers struct {
	Unmodeled []RawElement `xml:",any"`
}

type Trades struct {
	AssetSummary  []Trade `xml:"AssetSummary"`
	Lot           []Trade `xml:"Lot"`
	Order         []Trade `xml:"Order"`
	SymbolSummary []Trade `xml:"SymbolSummary"`
	Trade         []Trade `xml:"Trade"`
	WashSale      []Trade `xml:"WashSale"`
}

type TransactionTax struct {
	AccountID                 string `xml:"accountId,attr"`
	AcctAlias                 string `xml:"acctAlias,attr"`
	AssetCategory             string `xml:"assetCategory,attr"`
	Code                      string `xml:"code,attr"`
	CommodityType             string `xml:"commodityType,attr"`
	Conid                     string `xml:"conid,attr"`
	Currency                  string `xml:"currency,attr"`
	Cusip                     string `xml:"cusip,attr"`
	Date                      string `xml:"date,attr"`
	DeliveryType              string `xml:"deliveryType,attr"`
	Description               string `xml:"description,attr"`
	Expiry                    string `xml:"expiry,attr"`
	Figi                      string `xml:"figi,attr"`
	Fineness                  Float  `xml:"fineness,attr"`
	FxRateToBase              Float  `xml:"fxRateToBase,attr"`
	Isin                      string `xml:"isin,attr"`
	Issuer                    string `xml:"issuer,attr"`
	IssuerCountryCode         string `xml:"issuerCountryCode,attr"`
	LevelOfDetail             string `xml:"levelOfDetail,attr"`
	ListingExchange           string `xml:"listingExchange,attr"`
	Model                     string `xml:"model,attr"`
	Multiplier                Float  `xml:"multiplier,attr"`
	OrderID                   string `xml:"orderId,attr"`
	PrincipalAdjustFactor     string `xml:"principalAdjustFactor,attr"`
	PutCall                   string `xml:"putCall,attr"`
	Quantity                  Float  `xml:"quantity,attr"`
	ReportDate                string `xml:"reportDate,attr"`
	SecurityID                string `xml:"securityID,attr"`
	SecurityIDType            string `xml:"securityIDType,attr"`
	SerialNumber              string `xml:"serialNumber,attr"`
	SettleDate                string `xml:"settleDate,attr"`
	Source                    string `xml:"source,attr"`
	Strike                    Float  `xml:"strike,attr"`
	SubCategory               string `xml:"subCategory,attr"`
	Symbol                    string `xml:"symbol,attr"`
	TaxAmount                 Float  `xml:"taxAmount,attr"`
	TaxDescription            string `xml:"taxDescription,attr"`
	TradeID                   string `xml:"tradeId,attr"`
	TradePrice                Float  `xml:"tradePrice,attr"`
	UnderlyingConid           string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID      string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol          string `xml:"underlyingSymbol,attr"`
	Weight                    Float  `xml:"weight,attr"`
}

type TransactionTaxes struct {
	TransactionTax []TransactionTax `xml:"TransactionTax"`
}

type Transfers struct {
	Unmodeled []RawElement `xml:",any"`
}

type UnbundledCommissionDetail struct {
	AccountID                  string `xml:"accountId,attr"`
	AcctAlias                  string `xml:"acctAlias,attr"`
	AssetCategory              string `xml:"assetCategory,attr"`
	BrokerClearingCharge       Float  `xml:"brokerClearingCharge,attr"`
	BrokerExecutionCharge      Float  `xml:"brokerExecutionCharge,attr"`
	BuySell                    string `xml:"buySell,attr"`
	CommodityType              string `xml:"commodityType,attr"`
	Conid                      string `xml:"conid,attr"`
	Currency                   string `xml:"currency,attr"`
	Cusip                      string `xml:"cusip,attr"`
	DateTime                   string `xml:"dateTime,attr"`
	DeliveryType               string `xml:"deliveryType,attr"`
	Description                string `xml:"description,attr"`
	Exchange                   string `xml:"exchange,attr"`
	Expiry                     string `xml:"expiry,attr"`
	Figi                       string `xml:"figi,attr"`
	Fineness                   Float  `xml:"fineness,attr"`
	FxRateToBase               Float  `xml:"fxRateToBase,attr"`
	Isin                       string `xml:"isin,attr"`
	Issuer                     string `xml:"issuer,attr"`
	IssuerCountryCode          string `xml:"issuerCountryCode,attr"`
	ListingExchange            string `xml:"listingExchange,attr"`
	Model                      string `xml:"model,attr"`
	Multiplier                 Float  `xml:"multiplier,attr"`
	OrderReference             string `xml:"orderReference,attr"`
	Other                      Float  `xml:"other,attr"`
	Price                      Float  `xml:"price,attr"`
	PrincipalAdjustFactor      string `xml:"principalAdjustFactor,attr"`
	PutCall                    string `xml:"putCall,attr"`
	Quantity                   Float  `xml:"quantity,attr"`
	RegFINRATradingActivityFee Float  `xml:"regFINRATradingActivityFee,attr"`
	RegOther                   Float  `xml:"regOther,attr"`
	RegSection31TransactionFee Float  `xml:"regSection31TransactionFee,attr"`
	SecurityID                 string `xml:"securityID,attr"`
	SecurityIDType             string `xml:"securityIDType,attr"`
	SerialNumber               string `xml:"serialNumber,attr"`
	Strike                     Float  `xml:"strike,attr"`
	SubCategory                string `xml:"subCategory,attr"`
	Symbol                     string `xml:"symbol,attr"`
	ThirdPartyClearingCharge   Float  `xml:"thirdPartyClearingCharge,attr"`
	ThirdPartyExecutionCharge  Float  `xml:"thirdPartyExecutionCharge,attr"`
	ThirdPartyRegulatoryCharge Float  `xml:"thirdPartyRegulatoryCharge,attr"`
	TotalCommission            Float  `xml:"totalCommission,attr"`
	TradeID                    string `xml:"tradeID,attr"`
	UnderlyingConid            string `xml:"underlyingConid,attr"`
	UnderlyingListingExchange  string `xml:"underlyingListingExchange,attr"`
	UnderlyingSecurityID       string `xml:"underlyingSecurityID,attr"`
	UnderlyingSymbol           string `xml:"underlyingSymbol,attr"`
	Weight                     Float  `xml:"weight,attr"`
}

type UnbundledCommissionDetails struct {
	UnbundledCommissionDetail []UnbundledCommissionDetail `xml:"UnbundledCommissionDetail"`
}
